baseURL = "https://keertana.gollahalli.com/"
languageCode = "en-us"
title = "Dr. Keertana Gollahalli"
theme = "Indigo"

[params]
    linkedin = "https://www.linkedin.com/in/drkeertana/"
    photo = "keertana.JPG"
