[build]
publish = "public"
command = "hugo --gc --minify"

[context.deploy-preview.environment]
HUGO_VERSION = "0.111.3"

[context.production.environment]
HUGO_VERSION = "0.111.3"
HUGO_ENV = "production"
