[build]
publish = "public"
command = "hugo --gc --minify"

[context.deploy-preview.environment]
HUGO_VERSION = "0.69.2"

[context.production.environment]
HUGO_VERSION = "0.69.2"
HUGO_ENV = "production"
