[build]
publish = "public"
command = "hugo --gc --minify"

[context.deploy-preview.environment]
HUGO_VERSION = "0.82.0"

[context.production.environment]
HUGO_VERSION = "0.82.0"
HUGO_ENV = "production"
